let User,CustomErrorHandler;_4c5‍.x([["default",()=>_4c5‍.o]]);_4c5‍.w("../../models",[["User",["User"],function(v){User=v}]]);_4c5‍.w("../../services/CustomErrorHandler",[["default",["CustomErrorHandler"],function(v){CustomErrorHandler=v}]]);


const userController={
  async   me(req,res,next){
        try{
            const user=await User.findOne({_id:req.user._id}).select('-password -updatedAt -__v');
            if(!user){
                return next(CustomErrorHandler.notFound());
            }
            res.json(user);

        }catch(err){
                return next(err);
        }
     }
};


_4c5‍.d(userController);